name: Build, Test, Valgrind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  BUILD_OUT_DIR: build

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pkg-config
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-13 60
        sudo apt-get install -y tree
        sudo apt-get install -y ninja-build
        sudo apt-get install -y xvfb libgl1-mesa-dri libgl1-mesa-glx mesa-utils libgl1-mesa-dev libglu1-mesa-dev
        sudo apt-get install libx11-xcb-dev
        sudo apt-get install -y valgrind
        sudo apt-get install -y lcov
        sudo pip install conan==1.62.0
        conan profile new default --detect
        echo "[conf]\n" >> ~/.conan/profiles/default
        echo "tools.system.package_manager:sudo=True\n" >> ~/.conan/profiles/default
        echo "tools.system.package_manager:sudo_askpass=True\n" >> ~/.conan/profiles/default
        echo "tools.system.package_manager:mode=install" >> ~/.conan/profiles/default
        chmod +x coverage.sh    

    
    
    - name: Install sonar-scanner and build-wrapper
      uses: SonarSource/sonarcloud-github-c-cpp@v2

    - name: Create build directory
      run: mkdir -p ${{github.workspace}} ${{env.BUILD_OUT_DIR}}

#    - name: Cache build directory
#      id: cache-build
#      uses: actions/cache@v2
#      with:
#        path: |
#          /home/runner/.conan
#          ${{github.workspace}}/build
#        key: ${{ runner.os }}-build-${{ hashFiles('**/*.cpp''**/CMakeLists.txt', '**/conanfile.txt') }}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory
      run: cmake --preset linux-debug -B ${{github.workspace}}/${{env.BUILD_OUT_DIR}}

    - name: Run build-wrapper
      run: |
        build-wrapper-linux-x86-64 --out-dir ${{env.BUILD_OUT_DIR}} cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Run Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        sleep 3 # give xvfb some time to start

    - name: Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: build/bin/artist_tests

    - name: Component Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: build/bin/artist_component_tests

    - name: Coverage
      working-directory: ${{github.workspace}}
      run: |
        ./coverage.sh
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


    - name: Valgrind Test
      working-directory: ${{github.workspace}}
      run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes build/bin/artist_tests

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Run sonar-scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner