# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build, Test, Valgrind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pkg-config
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60
        sudo apt-get install -y ninja-build
        sudo apt-get install -y xvfb libgl1-mesa-dri libgl1-mesa-glx mesa-utils libgl1-mesa-dev libglu1-mesa-dev
        sudo apt-get install -y valgrind
        sudo apt-get install -y lcov
        sudo pip install conan==1.62.0
        conan profile new default --detect
        echo "[conf]\n" >> ~/.conan/profiles/default
        echo "tools.system.package_manager:sudo=True\n" >> ~/.conan/profiles/default
        echo "tools.system.package_manager:sudo_askpass=True\n" >> ~/.conan/profiles/default
        echo "tools.system.package_manager:mode=install" >> ~/.conan/profiles/default
        

    - name: Run Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        sleep 3 # give xvfb some time to start

    - name: Create build directory
      run: mkdir -p ${{github.workspace}} build

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake --preset linux-debug -B ${{github.workspace}}/build

    - name: Build
      # Build your pipeline with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: build/bin/cenpy-common_tests
    
    - name: Component Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: build/bin/cenpy-common_component_tests
    
    - name: Generate Coverage Report
      working-directory: ${{github.workspace}}/build/Cenpy/tests/CMakeFiles/cenpy-common_tests.dir/src
      run: |
        ls
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --remove coverage.info '*conan*' --output-file coverage.info
        lcov --remove coverage.info '*test*' --output-file coverage.info
        lcov --list coverage.info 

    - name: Valgrind Test
      working-directory: ${{github.workspace}}
      run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes build/bin/cenpy-common_tests
    
    - name: Analyze with SonarCloud
      # You can pin the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      with:
        # Additional arguments for the sonarcloud scanner
        args:
          # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
          # mandatory
          -Dsonar.projectKey=Djoe-Denne_Cenpy
          -Dsonar.organization=djoe-denne06
          -Dsonar.coverageReportPaths=./coverage.info
